sonar.projectKey=student-management
sonar.exclusions=Jenkinsfile,docker-compose.yml,application-local.properties,application-local.properties.example,.env,.env.example,**/src/test/resources/**
sonar.text.inclusions.exclusions=Jenkinsfile,docker-compose.yml,application-local.properties,application-local.properties.example,.env,.env.example,**/src/test/resources/**
