spring.application.name=student-management
spring.config.import=optional:file:./application-local.properties

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

spring.security.csrf.enabled=false

# Server configuration :
server.port=8089
server.servlet.context-path=/student
